# Generated by Django 4.2.11 on 2024-05-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_connection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Connection",
        ),
    ]
