# Generated by Django 4.2.11 on 2024-05-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_tweet_username_alter_tweet_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="username",
            new_name="user",
        ),
    ]
