# Generated by Django 4.2.11 on 2024-05-30 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_rename_username_tweet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
